import Header from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import Script from "next/script";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<head>
				{/* Favicon */}
				<link rel="shortcut icon" href="/img/logos/favicon.png" />
				<link
					rel="stylesheet"
					href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css"
					integrity="sha384-tViUnnbYAV00FLIhhi3v/dWt3Jxw4gZQcNoSCxCIFNJVCx7/D55/wXsrNIRANwdD"
					crossOrigin="anonymous"
				/>

				{/* Font Awesome rules are in plugins.css; webfonts are copied to /assets/fonts/ by scripts/copy-fontawesome.mjs on postinstall/build (from @fortawesome/fontawesome-free). */}

				{/* CSS */}
				<link rel="stylesheet" href="/assets/css/plugins.css" />
				<link rel="stylesheet" href="/assets/css/search.css" />
				<link rel="stylesheet" href="/assets/css/base.css" />
				<link rel="stylesheet" href="/assets/css/styles.css" />
			</head>

			<body>
				{/* Preloader */}
				<div id="preloader"></div>

				{/* Main Wrapper */}
				<div className="main-wrapper">
					<Header />
					{children}
					<Footer />
				</div>

				{/* JS Scripts */}
				<Script src="/assets/js/jquery.min.js" />
				<Script src="/assets/js/popper.min.js" />
				<Script src="/assets/js/bootstrap.min.js" />
				<Script src="/assets/js/core.min.js" />
				<Script src="/assets/js/search.js" />
				<Script src="/assets/js/main.js" />
				<Script src="/assets/js/plugins.js" />
				<Script src="/assets/js/scripts.js" />
			</body>
		</html>
	);
}
